import './globals.css';
import type { Metadata, Viewport, } from 'next';
import { Nunito } from 'next/font/google';
import { CronsProvider } from './contexts/crons';

const nunito = Nunito({
    subsets: ['latin'],
    weight: 'variable',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const viewport: Viewport = {
    width: 1
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={nunito.className}>
                <CronsProvider>{children}</CronsProvider>
            </body>
        </html>
    );
}
