import './globals.css';
import 'bootstrap/dist/css/bootstrap.css';
import type { Metadata } from 'next';
import Head from 'next/head';
import Script from 'next/script';
import { Nunito } from 'next/font/google';

const nunito = Nunito({
    weight: 'variable',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <Head>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <body className={nunito.className}>
                {children}
                <Script
                    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
                    integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
                    crossOrigin="anonymous"
                ></Script>
            </body>
        </html>
    );
}
