import './globals.css';
import type { Metadata } from 'next';
import Head from 'next/head';
import { Nunito } from 'next/font/google';
import { TodosProvider } from './contexts/todos';

const nunito = Nunito({
    subsets: ['latin'],
    weight: 'variable',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <Head>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <body className={nunito.className}>
                <TodosProvider>{children}</TodosProvider>
            </body>
        </html>
    );
}
